### ISSUE TITLE
Selected part of code is almost invisible

### ISSUE THREAD

**Issue by MatyCZ** [coeiico/jetbrains-nightfall-theme#11]
Select some part of code by double click. Selected part is almost invisible.

Selected part is `App`.

![image](https://user-images.githubusercontent.com/318575/130775515-137176cd-acfe-4337-bde6-03b006601688.png)

**Comment by coeiico** [comment]
I'll take a look at some colour variations to add some more contrast :)

**Comment by qbunt** [comment]
More contrast between those colors would help, but, this is pretty easy to tweak 

<img width="781" alt="image" src="https://user-images.githubusercontent.com/187095/157293944-817eb9e4-7423-4ce2-ae9a-87327f520e03.png">

**Comment by coeiico** [comment]
Sorry about the long wait, I had exams and I'm still recovering from an eye operation, I hope the next update made it a bit more visible. I'll leave this open just incase. 👍
