### ISSUE TITLE
Font and font size

### ISSUE THREAD

**Issue by MatyCZ** [coeiico/jetbrains-nightfall-theme#13]
It is necessary to change font and font size for editor and console? Every user has different resolution, display scale or preffered font.

For example I use on my monitors resolution _1440x2560_ and scale is set to _125%_. Color scheme default font and font size is too small (_Menlo_, _11_). Default IDE font is _JetBrains Mono_ with size _13_ (perfect for my usage).

**Theme default**
![fontSmall](https://user-images.githubusercontent.com/318575/133211047-7a39fadd-2a21-4ee9-8838-1a4c10768632.png)

**IDE default**
![fontNormal](https://user-images.githubusercontent.com/318575/133211195-2c2b4e79-c26f-4f6c-a0ca-0e1b6939430e.png)

**Comment by coeiico** [comment]
I never considered font sizes with different resolutions, thanks for brining this to my attention, I'll probably revert it back to the default 13 :)

**Comment by RezuanDzibov** [comment]
Hello. Font Size can be changed in Settings -> Editor -> Color Scheme -> Color Scheme Font

![Screenshot from 2022-06-28 23-25-58](https://user-images.githubusercontent.com/68289805/176278824-d581af39-936d-40cb-8c56-75ae4a7edb2e.png)

**Comment by coeiico** [comment]
The theme will no longer modify the editors font 204293350b5595deb6be8df86a12db74cc55f85a
