### ISSUE TITLE
Clone for VSC?

### ISSUE THREAD

**Issue by kxzo** [coeiico/jetbrains-nightfall-theme#17]
Pretty much self-explanatory, I guess.

I really *love* this theme and would love to have a similar/the same successor for vs code.
Are you planning to do so? (Or may I try converting it?)

**Comment by coeiico** [comment]
I'm glad you love it :) This theme was based on [horizon theme](https://horizontheme.netlify.app/#:~:text=Open%20the%20extensions%20sidebar%20in,and%20choose%20a%20Horizon%20variant.) but is no longer being updated, there also exists an extended version [horizon theme extended](https://marketplace.visualstudio.com/items?itemName=LanceWilhelm.horizon-extended) which I have not tried out.

I don't have any plans to port this theme over to vscode, so I'd be more than happy if you wanted to.

**Comment by kxzo** [comment]
I'll have a look at the extended version and would love to transfer your theme to vscode but the theme editor style (with handling of token customizations and so on), is vastly different than from jetbrains' theme editor style. So it would be a big challenge xd

**Comment by coeiico** [comment]
Yea they are quite dissimilar, but you do not have to burden yourself with it unless this is something you would enjoy, and if you do decide to transfer it, then there's no need to rush, take all the time you need :)

**Comment by kxzo** [comment]
> Yea they are quite dissimilar, but you do not have to burden yourself with it unless this is something you would enjoy, and if you do decide to transfer it, then there's no need to rush, take all the time you need :)

I've actually also already made a prototype (experimental version), you can find it on my profile and in the marketplace under "Nighfall Dimmed". xd

I don't have screenshots uploaded yet xd

**Comment by coeiico** [comment]
I've tried it out and it really looks amazing!

![Screenshot_20230213_020141](https://user-images.githubusercontent.com/74169522/218345186-a6d5ed1d-7446-41ab-8af2-7fe022a1c573.png)

Nice job, it's beautiful :)

**Comment by kxzo** [comment]
> I've tried it out and it really looks amazing!
> 
> ![Screenshot_20230213_020141](https://user-images.githubusercontent.com/74169522/218345186-a6d5ed1d-7446-41ab-8af2-7fe022a1c573.png)
> 
> Nice job, it's beautiful :)

I actually completely redesigned it for now and there might be some big improvements in the the style for you, dunno what version you have installed.

Yeah, I totally redesigned the theme as well as the github page.

**Comment by coeiico** [comment]
I would like to add a link to your VSCode implementation of the theme to this theme's main page, also I would like to get in contact with you if you could please send me an email `brandiicoetzee@gmail.com`

**Comment by kxzo** [comment]
> I would like to add a link to your VSCode implementation of the theme to this theme's main page, also I would like to get in contact with you if you could please send me an email `brandiicoetzee@gmail.com`

Sounds good. I wrote you an email, using `einknuffy@gmail.com`
