### ISSUE TITLE
Add support for IntelliJ 2023.1

### ISSUE THREAD

**Issue by hnorkowski** [coeiico/jetbrains-nightfall-theme#18]
The plugin is not compatible with the most recent IntelliJ version 2023.1

**Comment by coeiico** [comment]
Support for 2023.1 has been added,

to avoid waiting for marketplace approval here is a direct download link: https://plugins.jetbrains.com/plugin/16142-nightfall-theme/versions/stable/313313

I will close the issue once the plugin has been approved :)

**Comment by hnorkowski** [comment]
Thank you very much :) love the theme <3

**Comment by coeiico** [comment]
And thank you for the support :) :+1:
