### ISSUE TITLE
Request - Coverage highlighting and other tweaks

### ISSUE THREAD

**Issue by karlmiles** [coeiico/jetbrains-nightfall-theme#2]
Hi, I'm really liking the theme!  Just a couple of small requests (if they're possible and you approve):

- Would you be able to set some background colours for code coverage?  By that, I mean when say PhpStorm highlights the lines that have been covered (or not) in tests.

- Not sure if this one's doable to be honest - the carat row highlighting in the project tree?  If the contrast could be increased so it's more easily to see.  Working on large projects, I often jump to a file though the search type keyboard shortcuts, and then maybe click the button to highlight the currently open file.  It's then where I've noticed I have to look hard to tell which one it is.  I think the row highlight in the main edit window's fine; I'm just not sure it's independent of the tree listing.

- When your cursor's in a variable for example, making the highlighting of its other uses more visible.

Thanks for sharing your work, and apologies if you're not looking for suggestions or anything like that.

**Comment by coeiico** [comment]
Thank you, I really appreciate the feedback!

Anyway I can contact you to get more details about your suggestions?

**Comment by coeiico** [comment]
@karlmiles background colors for code coverage will be available in v1.0.7

**Comment by karlmiles** [comment]
Cool!  Thanks for that, and apologies not getting back to you sooner.

**Comment by karlmiles** [comment]
Hi, these are the coverage settings I was thinking of:

![image](https://user-images.githubusercontent.com/2984054/109673094-9700dd00-7b6d-11eb-991e-c94aad7ec01b.png)

If I transfer the foreground colours to the background instead, I can more easily see what's covered in my tests, e.g.:

![image](https://user-images.githubusercontent.com/2984054/109673432-ef37df00-7b6d-11eb-8276-559b96d18791.png)

Apologies if I'd not noticed the markers in the gutter (which are visible in the theme without me making any changes) - It's probably a "me thing", wanting something like this to be very obvious.  If you're not keen, I don't mind just duplicating your colour scheme in my IDE and overriding things - do you have a list of hex codes for the colour palette?

**Comment by coeiico** [comment]
Yea in the changes made for v1.0.7 I changed the code coverage background colors which should produce the results that you wanted, highlighting the entire line and not just showing markers in the gutter, however I used the wrong colors for v1.0.7 and it should be correct for v1.0.8 which should be approved and available publicly in a few hours.

**Comment by karlmiles** [comment]
Brilliant, thank you for implementing that change!  It's a really nice theme to use - I spend a good 10 hours a day with it both on my work machine and personal, across various IDEs too.

**Comment by coeiico** [comment]
Not a problem, and I'm glad that you're loving the theme! If you'd like, can you elaborate more on your third point?
"When your cursor's in a variable for example, making the highlighting of its other uses more visible."

**Comment by karlmiles** [comment]
Ah, yeah, no problem.  My cursor's currently inside a `$this` variable:

![image](https://user-images.githubusercontent.com/2984054/109867531-85e3c900-7c5e-11eb-9966-d23f05998663.png)

I've just set a bright yellow border just so it really shows up (though it's actually a poor choice seeing as the carat's now hard to spot!):

![image](https://user-images.githubusercontent.com/2984054/109868254-52ee0500-7c5f-11eb-949e-536056d418ae.png)

![image](https://user-images.githubusercontent.com/2984054/109868002-0dc9d300-7c5f-11eb-9915-9ca357212cfa.png)

I don't know what you think to some alternative styling for todo comments - just so they stand out?  I know you can list your todos, search for them, etc., but, sometimes, it's handy to have them really visible when scanning files, particularly if they're quite long.  For me, these are very different to a code comment, it's either a reminder that I need to handle something before raising a PR, or maybe it's done and it needs to be removed.

Hope that helps show what I was meaning; I should've given you some screenshots in the original post, apologies.  You might look at it and think, "Wow!  I couldn't work with those border things flashing all over the place!" :D  They're only suggestions, they're not me pointing at things shouting, "Hey, that's wrong! Fix it!" :+1:

**Comment by karlmiles** [comment]
What I might do, is export your colour scheme and my tweaked version and see how easily they are to diff... that way, if I do end up with a bunch of personal preferences that aren't in fitting with the project, I can still keep track of your scheme and just re-apply essentially my overrides over the top.

**Comment by karlmiles** [comment]
I should also mention, there's a couple of plugins at work in those screenshots; Rainbow Brackets & Indent Rainbow.  Just in case your were wondering what's going on.  I think I've also muted the whitespace dots too.

**Comment by coeiico** [comment]
Alright gotcha, I've made the highlighting more visible for variables so it's easier to spot them.
TODO comments should stand out more, I've changed the background colors for them. I'm not sure if you wanted more contrast with the todo comments but I'm quite happy with this:
![wasd](https://user-images.githubusercontent.com/74169522/110218285-8af48280-7ec1-11eb-8c1a-cefd09e444dd.PNG)
These changes should be available in the next update 😉

**Comment by karlmiles** [comment]
Brilliant!  Looking forward to giving it a go.  Thanks for taking those changes on, it's appreciated.

I did get a chance to export the colour schemes and diff them... it'll be easy enough to maintain my own overrides and merge them together; it's just XML and where you don't have a setting and I do, there's additional lines in the relevant section.  I don't think there'll be many now though, but if there's anything specific that I find that's missing, I'll let you know.   Cheers again for sharing your work and your time :)

**Comment by coeiico** [comment]
No problem, and thank you again for the feedback, it's really appreciated.

@all-contributors add @karlmiles for ideas
