### ISSUE TITLE
2.0.0 white background editor

### ISSUE THREAD

**Issue by Jordan-Kowal** [coeiico/jetbrains-nightfall-theme#22]
As some of the latest reviews have said, the `2.0.0` update has broken the editor windows, which now shows everything in a white background:

![Capture d’écran 2023-11-20 à 10 28 07](https://github.com/coeiico/jetbrains-nightfall-theme-migration/assets/49999573/919ed317-3d6d-4cc6-b6b4-d52ee482c303)

**Comment by Styr1x** [comment]
Check your Color Scheme settings (Editor > Color Scheme) - if a theme is active on update the IDEs sometimes reset this to a default white; just select nightfall there and everything should work.

**Comment by Jordan-Kowal** [comment]
Oh man you're right. Didn't expect PyCharm to dissociate my theme and my editor color scheme. I didn't think of checking that. Sorry for that and thanks for the quick reply! ❤️
