### ISSUE TITLE
CLion 2023.2.5 White Background

### ISSUE THREAD

**Issue by heavycircle** [coeiico/jetbrains-nightfall-theme#23]
The editor background appears white in the latest CLion update. Side panels have a normal background color, but the coding panel and terminal have white backgrounds.

Thanks for helping fix this!

**Comment by FelixBlaimauer** [comment]
Same here in IntelliJ

![grafik](https://github.com/coeiico/jetbrains-nightfall-theme-migration/assets/78758612/a9a45358-337f-42a1-86c1-220536d3aa47)

**Comment by FelixBlaimauer** [comment]
Found a simple fix
Open search with Shift+Shift, Search for "Editor Color Scheme" and set it to nightfall aswell

**Comment by heavycircle** [comment]
Worked a treat, thank you!
