### ISSUE TITLE
VCS Diff Readability

### ISSUE THREAD

**Issue by karlmiles** [coeiico/jetbrains-nightfall-theme#7]
Hi, came across an issue whilst working today, where diffs aren't really readable.  Here's a screenshot of the settings and the example rendering:

![image](https://user-images.githubusercontent.com/2984054/110962256-ad1a5480-8348-11eb-8d73-21132c9f77ba.png)

Would you be able to tweak the colours at all?  Given they don't give you options for foregrounds on these, you might just need to darken the backgrounds a fair bit?

**Comment by coeiico** [comment]
Hmm this seems to be a transparency issue again, I'll fix it, this it what it looks like on my system:

![issue](https://user-images.githubusercontent.com/74169522/110970151-1fe3f980-8362-11eb-8dc3-704367ec8bc4.PNG)

**Comment by coeiico** [comment]
Check out release v1.1.1 and let me know if it solved your issue 👍

**Comment by karlmiles** [comment]
Excellent!  Yep, that's resolved it, thank you :)
