### ISSUE TITLE
Please add support for 2021.2

### ISSUE THREAD

**Issue by imri29** [coeiico/jetbrains-nightfall-theme#8]
![2021-07-27 09_11_55-WebStorm and Plugin Updates (Ubuntu)](https://user-images.githubusercontent.com/30725898/127104665-6bb658a3-0d9c-414f-b4a6-5d20fd5401f6.png)

**Comment by Paracells** [comment]
And fix problem with background color of window for 2021.2
![fix](https://user-images.githubusercontent.com/575811/127126266-70b5a3b2-0d52-418d-83cf-0613d35f009d.jpg)

**Comment by coeiico** [comment]
Support for 2021.2 had been added and will be available in due time. For now you can download and install it manually [here](https://github.com/brandii-co/jetbrains-nightfall-theme/releases/tag/v1.1.2).
