### ISSUE TITLE
Problem with code complete window background color

### ISSUE THREAD

**Issue by coeiico** [coeiico/jetbrains-nightfall-theme#9]
This was first pointed out by Paracells, but I can't find the original comment. The newer versions of jetbrains IDEs might have an issue with the background color of this window:

![127126266-70b5a3b2-0d52-418d-83cf-0613d35f009d](https://user-images.githubusercontent.com/74169522/127426110-99c954a4-467d-4147-bc0a-c7c6e2db413e.jpg)

**Comment by Paracells** [comment]
I deleted the issue, I thought it was me that somehow updated crookedly.
![Screenshot 2021-07-29 072007](https://user-images.githubusercontent.com/575811/127431418-ed7789cd-136b-4783-ba04-c1c0883468f4.jpg)

**Found**. You should change `<option name="LOOKUP_COLOR" value="" />` in nightfall.xml. Now there is no this parameter, but if you change what is in the picture, then it will appear

**Comment by coeiico** [comment]
Thank you that worked perfectly :)

@all-contributors add @Paracells for bug and code
